---
- name: Converge
  hosts: all

  vars_files:
    - ../../vars/molecule_vars.yml

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true
      when: ansible_os_family == 'Debian'

    - name: Create test user
      ansible.builtin.user:
        name: testuser
        state: present
        create_home: true
      become: true

  roles:
    - role: pluggero.tigervnc
