---
- name: Verify
  hosts: all
  gather_facts: true

  vars_files:
    - ../../defaults/main.yml

  tasks:
    - name: Include OS-specific variables
      ansible.builtin.include_vars: "{{ var_file }}"
      with_first_found:
        - "{{ role_path }}/vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/vars/{{ ansible_distribution }}.yml"
        - "{{ role_path }}/vars/{{ ansible_os_family }}.yml"
        - "{{ role_path }}/vars/{{ ansible_lsb.id }}.yml"
      loop_control:
        loop_var: var_file

    - name: Check installed version
      ansible.builtin.include_tasks: "../../tasks/noauto_check_installed_version.yml"

    - name: Assert installed version is correct
      ansible.builtin.assert:
        that:
          - "tigervnc_installed_version == tigervnc_version"
