---
- name: Verify
  hosts: all
  gather_facts: true

  vars_files:
    - ../../defaults/main.yml

  tasks:
    - name: Include OS-specific variables
      ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
      vars:
        params:
          files:
            - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
            - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
            - "{{ ansible_distribution }}.yml"
            - "{{ ansible_os_family }}.yml"
          paths:
            - "../../vars"

    - name: Check installed version
      ansible.builtin.include_tasks: "../../tasks/noauto_check_installed_version.yml"

    - name: Assert installed version is correct
      ansible.builtin.assert:
        that:
          - "tigervnc_installed_version == tigervnc_version"
