---
- name: Verify
  hosts: all
  gather_facts: true

  vars_files:
    - ../../defaults/main.yml

  tasks:
    - name: Include OS-specific variables
      ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
      vars:
        params:
          files:
            - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
            - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
            - "{{ ansible_distribution }}.yml"
            - "{{ ansible_os_family }}.yml"
          paths:
            - "../../vars"

    - name: Verify TigerVNC Installation
      tags: [verify_installation]
      block:
        - name: Check installed version
          ansible.builtin.include_tasks: "../../tasks/noauto_check_installed_version.yml"

        - name: Assert installed version is correct
          ansible.builtin.assert:
            that:
              - "tigervnc_installed_version == tigervnc_version"
            fail_msg: "TigerVNC version mismatch: expected {{ tigervnc_version }}, found {{ tigervnc_installed_version }}"
            success_msg: "TigerVNC version {{ tigervnc_version }} is correctly installed"

        - name: Check TigerVNC binaries are in PATH
          ansible.builtin.command:
            cmd: "which {{ item }}"
          register: tigervnc_binaries_which
          changed_when: false
          failed_when: false
          loop:
            - "{{ tigervnc_viewer_bin }}"
            - "{{ tigervnc_server_bin }}"
            - "{{ tigervnc_passwd_bin }}"

        - name: Assert all TigerVNC binaries are available in PATH
          ansible.builtin.assert:
            that:
              - item.rc == 0
            fail_msg: "Binary {{ item.item }} is not found in PATH"
            success_msg: "Binary {{ item.item }} is available in PATH"
          loop: "{{ tigervnc_binaries_which.results }}"
          loop_control:
            label: "{{ item.item }}"

    - name: Verify Multi-User Configuration
      tags: [verify_configuration]
      block:
        - name: Verify configuration for each user
          ansible.builtin.include_tasks: noauto_verify_user.yml
          loop: "{{ tigervnc_users }}"
          loop_control:
            loop_var: vnc_user

        - name: Check vncserver.users file exists
          ansible.builtin.stat:
            path: /etc/tigervnc/vncserver.users
          register: tigervnc_users_file_stat
          become: true

        - name: Assert vncserver.users file exists
          ansible.builtin.assert:
            that:
              - tigervnc_users_file_stat.stat.exists
            fail_msg: "vncserver.users file is missing"
            success_msg: "vncserver.users file exists"

        - name: Verify user to display mappings
          ansible.builtin.lineinfile:
            path: /etc/tigervnc/vncserver.users
            line: ":{{ item.display }}={{ item.username }}"
            state: present
          check_mode: true
          register: tigervnc_user_mappings
          loop: "{{ tigervnc_users }}"
          become: true

        - name: Assert all user to display mappings are present
          ansible.builtin.assert:
            that:
              - not item.changed
            fail_msg: "User to display mapping ':{{ item.item.display }}={{ item.item.username }}' is missing"
            success_msg: "User to display mapping for {{ item.item.username }} is correct"
          loop: "{{ tigervnc_user_mappings.results }}"
          loop_control:
            label: "{{ item.item.username }}"

    - name: Verify TigerVNC Service Configuration
      tags: [verify_service]
      block:
        - name: Check systemd template service file exists
          ansible.builtin.stat:
            path: "/etc/systemd/system/vncserver@.service"
          register: tigervnc_template_service_stat
          become: true

        - name: Assert systemd template service file exists
          ansible.builtin.assert:
            that:
              - tigervnc_template_service_stat.stat.exists
            fail_msg: "Systemd template service file vncserver@.service is missing"
            success_msg: "Systemd template service file vncserver@.service exists"

        - name: Verify service for each user
          ansible.builtin.include_tasks: noauto_verify_service.yml
          loop: "{{ tigervnc_users }}"
          loop_control:
            loop_var: vnc_user

    - name: Verify Package Dependencies
      tags: [verify_dependencies]
      block:
        - name: Check required Perl modules directory exists
          ansible.builtin.stat:
            path: /usr/local/lib/perl5/TigerVNC
          register: tigervnc_perl_dir_stat
          become: true

        - name: Assert Perl modules directory exists
          ansible.builtin.assert:
            that:
              - tigervnc_perl_dir_stat.stat.exists
              - tigervnc_perl_dir_stat.stat.isdir
            fail_msg: "TigerVNC Perl modules directory is missing"
            success_msg: "TigerVNC Perl modules directory exists"

        - name: Check TigerVNC Perl wrapper exists
          ansible.builtin.stat:
            path: /usr/local/bin/tigervnc_wrapper
          register: tigervnc_wrapper_stat
          become: true

        - name: Assert TigerVNC Perl wrapper exists and is executable
          ansible.builtin.assert:
            that:
              - tigervnc_wrapper_stat.stat.exists
              - tigervnc_wrapper_stat.stat.executable
            fail_msg: "TigerVNC Perl wrapper is missing or not executable"
            success_msg: "TigerVNC Perl wrapper exists and is executable"

        - name: Check required Perl modules exist
          ansible.builtin.stat:
            path: "/usr/local/lib/perl5/TigerVNC/{{ item }}"
          register: tigervnc_perl_modules_stat
          become: true
          loop:
            - Common.pm
            - Config.pm
            - Wrapper.pm
            - OptionTie.pm

        - name: Assert all required Perl modules are present
          ansible.builtin.assert:
            that:
              - item.stat.exists
            fail_msg: "Perl module {{ item.item }} is missing"
            success_msg: "Perl module {{ item.item }} exists"
          loop: "{{ tigervnc_perl_modules_stat.results }}"
          loop_control:
            label: "{{ item.item }}"

        - name: Verify system configuration directory exists
          ansible.builtin.stat:
            path: /etc/tigervnc
          register: tigervnc_etc_dir_stat
          become: true

        - name: Assert system configuration directory exists
          ansible.builtin.assert:
            that:
              - tigervnc_etc_dir_stat.stat.exists
              - tigervnc_etc_dir_stat.stat.isdir
            fail_msg: "System configuration directory /etc/tigervnc is missing"
            success_msg: "System configuration directory /etc/tigervnc exists"
